//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsocketProtocal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class siyosane_uwb_prototypeEntities : DbContext
    {
        public siyosane_uwb_prototypeEntities()
            : base("name=siyosane_uwb_prototypeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Device> tb_Device { get; set; }
        public virtual DbSet<tb_account> tb_account { get; set; }
        public virtual DbSet<tb_BlockZone> tb_BlockZone { get; set; }
        public virtual DbSet<tb_BlockZoneDetail> tb_BlockZoneDetail { get; set; }
        public virtual DbSet<tb_Department> tb_Department { get; set; }
        public virtual DbSet<tb_Floorplan> tb_Floorplan { get; set; }
        public virtual DbSet<tb_GPSLocation> tb_GPSLocation { get; set; }
        public virtual DbSet<tb_HistoryZone> tb_HistoryZone { get; set; }
        public virtual DbSet<tb_MQTT> tb_MQTT { get; set; }
        public virtual DbSet<tb_Site> tb_Site { get; set; }
        public virtual DbSet<tb_Staff> tb_Staff { get; set; }
        public virtual DbSet<tb_tracker> tb_tracker { get; set; }
        public virtual DbSet<tb_UWBLocation> tb_UWBLocation { get; set; }
    }
}
