//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsocketProtocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Device
    {
        public int ID { get; set; }
        public string DeviceName { get; set; }
        public string DeviceMAC { get; set; }
        public string DeviceID { get; set; }
        public string isType { get; set; }
        public Nullable<int> isSiteID { get; set; }
        public Nullable<double> posX { get; set; }
        public Nullable<double> posY { get; set; }
        public Nullable<double> posZ { get; set; }
        public Nullable<double> posQ { get; set; }
        public Nullable<int> SeatNumber { get; set; }
        public string Colors { get; set; }
        public Nullable<int> IsShow { get; set; }
    }
}
