//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsocketProtocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HistoryZone
    {
        public int Id { get; set; }
        public string TagId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string ZoneName { get; set; }
        public Nullable<int> States { get; set; }
        public Nullable<System.DateTime> Ins { get; set; }
        public Nullable<System.DateTime> Out { get; set; }
    }
}
