//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsocketProtocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MQTT
    {
        public int ID { get; set; }
        public string TopicName { get; set; }
        public string MQTTUser { get; set; }
        public string MQTTPassword { get; set; }
        public string MQTTServer { get; set; }
        public Nullable<int> MQTTWebsocketPort { get; set; }
        public Nullable<int> MQTTNormalPort { get; set; }
        public Nullable<int> MQTTSecurePort { get; set; }
    }
}
