//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsocketProtocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Site
    {
        public int ID { get; set; }
        public string SiteName { get; set; }
        public Nullable<int> CanvasWidth { get; set; }
        public Nullable<int> CanvasHeight { get; set; }
        public Nullable<int> InitiatorX { get; set; }
        public Nullable<int> InitiatorY { get; set; }
        public Nullable<int> SiteDistance { get; set; }
        public Nullable<double> isRatio { get; set; }
        public Nullable<double> isRatioDefault { get; set; }
        public Nullable<double> isRatioZoom { get; set; }
    }
}
