//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsocketProtocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Staff
    {
        public int StaffID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_Department { get; set; }
        public string Address { get; set; }
        public Nullable<int> Id_Site { get; set; }
        public Nullable<int> ID_Device { get; set; }
        public string Email { get; set; }
        public string Images { get; set; }
    }
}
