//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsocketProtocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tracker
    {
        public int ID { get; set; }
        public string TrackerID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> TopicID { get; set; }
    }
}
