//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsocketProtocal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UWBLocation
    {
        public int ID { get; set; }
        public string gatewayID { get; set; }
        public string gatewayMAC { get; set; }
        public string tagID { get; set; }
        public string tagMAC { get; set; }
        public string getX { get; set; }
        public string getY { get; set; }
        public string getZ { get; set; }
        public string getRSSI { get; set; }
        public Nullable<System.DateTime> atTime { get; set; }
        public Nullable<int> ZoneID { get; set; }
    }
}
